theme: jekyll-theme-cayman
title: Bienvenue à salut.yoga
description: salut n. m.
1 Préservation de la vie. Les passagers n'ont dû leur salut qu'à leur ceinture de sécurité.
2 Bonheur éternel. Le salut de l’âme.
3 Salutation. Faire un salut de la main. | Salut! | Je te verrai demain!
Planche de salut.
(fig.) Ressource ultime.

